// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ChunkedUploadChunk struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	ChunkIndex     int32
	ChunkSizeBytes int32
	StoragePath    sql.NullString
	Checksum       sql.NullString
	ReceivedAt     sql.NullTime
	ProcessedAt    sql.NullTime
}

type ChunkedUploadSession struct {
	ID               uuid.UUID
	SessionID        string
	RecordingID      uuid.UUID
	UserID           uuid.UUID
	TemplateID       uuid.UUID
	EncounterID      uuid.NullUUID
	PatientID        uuid.NullUUID
	ScribeSessionID  sql.NullString
	Status           sql.NullString
	TotalChunks      sql.NullInt32
	ChunksReceived   sql.NullInt32
	ChunkStoragePath sql.NullString
	Metadata         pqtype.NullRawMessage
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	ExpiresAt        sql.NullTime
	FinalizedAt      sql.NullTime
	UploadStartTime  sql.NullTime
	UploadEndTime    sql.NullTime
	UploadDurationMs sql.NullInt32
	TotalSizeBytes   sql.NullInt64
}

type ClinicalNote struct {
	ID               uuid.UUID
	EncounterID      uuid.UUID
	TemplateID       uuid.UUID
	UserID           uuid.UUID
	Content          string
	ExtractedData    pqtype.NullRawMessage
	Status           string
	ExtractionMethod sql.NullString
	SignedAt         sql.NullTime
	SignedBy         uuid.NullUUID
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type DiagnosticResult struct {
	ID             uuid.UUID
	EncounterID    uuid.UUID
	TestName       string
	TestType       sql.NullString
	ResultValue    sql.NullString
	ResultUnit     sql.NullString
	ReferenceRange sql.NullString
	Status         string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Encounter struct {
	ID            uuid.UUID
	PatientID     uuid.UUID
	UserID        uuid.UUID
	EncounterType sql.NullString
	Status        string
	Notes         sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	CompletedAt   sql.NullTime
}

type Note struct {
	ID               uuid.UUID
	PatientID        uuid.NullUUID
	RecordingID      uuid.NullUUID
	EncounterID      uuid.NullUUID
	CreatedBy        uuid.UUID
	UpdatedBy        uuid.NullUUID
	Title            string
	Content          string
	NoteType         string
	Status           string
	ScribePageID     sql.NullString
	Tags             pqtype.NullRawMessage
	Metadata         pqtype.NullRawMessage
	ExtractionMethod sql.NullString
	PromptVersion    sql.NullString
	IsSigned         sql.NullBool
	SignedAt         sql.NullTime
	SignedBy         uuid.NullUUID
	Version          sql.NullInt32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Order struct {
	ID          uuid.UUID
	EncounterID uuid.UUID
	OrderType   string
	Description string
	Status      string
	OrderedBy   uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Organization struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Patient struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	DateOfBirth         sql.NullTime
	Gender              sql.NullString
	Email               sql.NullString
	Phone               sql.NullString
	MedicalRecordNumber sql.NullString
	OrganizationID      uuid.UUID
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type Recording struct {
	ID                   uuid.UUID
	EncounterID          uuid.NullUUID
	UserID               uuid.UUID
	PatientID            uuid.NullUUID
	TemplateID           uuid.UUID
	AudioFileUrl         sql.NullString
	AudioDurationSeconds sql.NullInt32
	Status               string
	Transcription        sql.NullString
	Analysis             pqtype.NullRawMessage
	RawExtraction        pqtype.NullRawMessage
	ExtractionPromptUsed sql.NullString
	ProcessingError      sql.NullString
	ProcessingTimeMs     sql.NullInt32
	ScribePageID         sql.NullString
	IsLinked             sql.NullBool
	LinkedAt             sql.NullTime
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	SessionID            sql.NullString
	UploadSessionID      uuid.NullUUID
	UploadMethod         sql.NullString
	UploadDurationMs     sql.NullInt32
}

type ScribeSession struct {
	SessionID   string
	UserID      uuid.UUID
	PatientID   uuid.NullUUID
	EncounterID uuid.NullUUID
	TemplateID  uuid.UUID
	Status      string
	Version     int32
	Metadata    pqtype.NullRawMessage
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	ExpiresAt   sql.NullTime
}

type SessionAuditLog struct {
	ID           uuid.UUID
	SessionID    string
	UserID       uuid.UUID
	Action       string
	ResourceType sql.NullString
	ResourceID   sql.NullString
	OldValue     pqtype.NullRawMessage
	NewValue     pqtype.NullRawMessage
	Metadata     pqtype.NullRawMessage
	CreatedAt    sql.NullTime
}

type Task struct {
	ID          uuid.UUID
	EncounterID uuid.UUID
	Title       string
	Description sql.NullString
	Status      string
	AssignedTo  uuid.NullUUID
	CreatedBy   uuid.UUID
	DueDate     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Template struct {
	ID                 uuid.UUID
	TemplateKey        string
	Label              string
	Description        sql.NullString
	Specialty          sql.NullString
	Category           sql.NullString
	Prompt             string
	ExtractStyle       sql.NullString
	PromptVersion      sql.NullInt32
	PromptLastModified sql.NullTime
	Metadata           pqtype.NullRawMessage
	IsActive           sql.NullBool
	CreatedBy          uuid.NullUUID
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type TranscriptSegment struct {
	ID               uuid.UUID
	RecordingID      uuid.UUID
	Speaker          sql.NullString
	Text             string
	StartTimeSeconds sql.NullString
	EndTimeSeconds   sql.NullString
	Confidence       sql.NullString
	CreatedAt        sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	Password       string
	FirstName      sql.NullString
	LastName       sql.NullString
	Role           string
	OrganizationID uuid.NullUUID
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	LastLogin      sql.NullTime
}
